void CloseWindow(void);
bool WindowShouldClose(void);
bool IsWindowReady(void);
bool IsWindowFullscreen(void);
bool IsWindowHidden(void);
bool IsWindowMinimized(void);
bool IsWindowMaximized(void);
bool IsWindowFocused(void);
bool IsWindowResized(void);
void ToggleFullscreen(void);
void ToggleBorderlessWindowed(void);
void MaximizeWindow(void);
void MinimizeWindow(void);
void RestoreWindow(void);
void SetWindowFocused(void);
void *GetWindowHandle(void);
int GetScreenWidth(void);
int GetScreenHeight(void);
int GetRenderWidth(void);
int GetRenderHeight(void);
int GetMonitorCount(void);
int GetCurrentMonitor(void);
const char *GetClipboardText(void);
void EnableEventWaiting(void);
void DisableEventWaiting(void);
void ShowCursor(void);
void HideCursor(void);
bool IsCursorHidden(void);
void EnableCursor(void);
void DisableCursor(void);
bool IsCursorOnScreen(void);
void BeginDrawing(void);
void EndDrawing(void);
void EndMode2D(void);
void EndMode3D(void);
void EndTextureMode(void);
void EndShaderMode(void);
void EndBlendMode(void);
void EndScissorMode(void);
void EndVrStereoMode(void);
float GetFrameTime(void);
double GetTime(void);
int GetFPS(void);
void SwapScreenBuffer(void);
void PollInputEvents(void);
const char *GetWorkingDirectory(void);
const char *GetApplicationDirectory(void);
bool IsFileDropped(void);
void StartAutomationEventRecording(void);
void StopAutomationEventRecording(void);
int GetKeyPressed(void);
int GetCharPressed(void);
int GetGamepadButtonPressed(void);
int GetMouseX(void);
int GetMouseY(void);
float GetMouseWheelMove(void);
int GetTouchX(void);
int GetTouchY(void);
int GetTouchPointCount(void);
int GetGestureDetected(void);
float GetGestureHoldDuration(void);
float GetGestureDragAngle(void);
float GetGesturePinchAngle(void);



Vector2 GetGestureDragVector(void);
Vector2 GetGesturePinchVector(void);
Vector2 GetMouseWheelMoveV(void);
Vector2 GetMousePosition(void);
Vector2 GetMouseDelta(void);
FilePathList LoadDroppedFiles(void);
Image GetClipboardImage(void);
Vector2 GetWindowPosition(void);
Vector2 GetWindowScaleDPI(void);

